from __future__ import annotations

import numpy as np
import torch
from pydantic import BaseModel, ConfigDict


class DetectionModelOutput(BaseModel):
    """
    Output of the detection model after running inference on the preprocessed video
    
    Attributes:
    - annotated_frames (list[DetectionFrame]): A list of detected frames with their corresponding bounding boxes and labels.
    - preprocessed_video (PreprocessedVideo): The preprocessed video that was passed into the detection model.
    """
    model_config = ConfigDict(arbitrary_types_allowed=True)

    annotated_frames: list["DetectionFrame"]
    preprocessed_video: "PreprocessedVideo"

class PreprocessedVideo(BaseModel):
    """
    Preprocessed video data.

    Attributes:
    - frames (np.ndarray | torch.Tensor): A list of frames to be processed, each frame is a numpy array or a torch tensor.'
    - step_names (list[str]): Names of preprocessing steps applied to the video.
    - num_tiles (int | None): If resize was used, this is the number of tiles that make up a frame. If resize was not used, this is None.
    - tile_offset (tuple[int, int] | None): If resize was used, this is the (step_x, step_y) stride between adjacent tile origins in the original frame. If resize was not used, this is None.
    - tile_positions (list[tuple[int, int]] | None): If resize was used, this is the (x, y) starting pixel of each tile in the original frame, indexed 0..num_tiles-1. Uniform across all frames.
    - source_video_path (str): Path to the original (unpreprocessed) source video, used by downstream stages (e.g. the postprocessor) to render the annotated video at the original resolution.

    NOTE: if resizing is done, then there could be multiple frames in the frame object per frame in the video.
    """
    model_config = ConfigDict(arbitrary_types_allowed=True)

    frames: "np.ndarray | torch.Tensor"
    step_names: list[str]
    num_tiles: "int | None" = None
    tile_offset: "tuple[int, int] | None" = None
    tile_positions: "list[tuple[int, int]] | None" = None
    source_video_path: str

class DetectionFrame(BaseModel):
    """
    The detected objects for a single frame of the video. For standardizing the outputs of different detection models into one format.

    Attributes:
    - frame_number (int): The frame number of the video that this detection corresponds to.
    - xyxy (np.ndarray | torch.Tensor): The bounding boxes of the detected objects in the frame, in xyxy format.
    - xywh (np.ndarray | torch.Tensor): The bounding boxes of the detected objects in the with the center of the box and the dimension of the box.
    - xyxyn (np.ndarray | torch.Tensor): The bounding boxes of the detected objects in the frame, in xyxy format, normalized to the size of the frame.
    - conf (np.ndarray | torch.Tensor): The confidence scores of the detected objects in the frame.
    - cls (np.ndarray | torch.Tensor): The class labels of the detected objects in the frame.
    """
    model_config = ConfigDict(arbitrary_types_allowed=True)

    frame_number: int
    xyxy: "np.ndarray | torch.Tensor"
    xywh: "np.ndarray | torch.Tensor"
    xyxyn: "np.ndarray | torch.Tensor"
    conf: "np.ndarray | torch.Tensor"
    cls: "np.ndarray | torch.Tensor"

class PostprocessorOutput(BaseModel):
    """
    Output event data for the detection module. This represents all of the different objects that were detected from the detection module and their corresponding locations in the video.

    Attribute:
    - output_video_path (str): The path to the annotated video that was generated by the detection module.
    - annotated_frames (list[DetectionFrame]): A list of detected frames with their corresponding bounding boxes and labels.
    """
    model_config = ConfigDict(arbitrary_types_allowed=True)

    output_video_path: str
    annotated_frames: list[DetectionFrame]
    version: str = "0.1.0"

class DetectionInput(BaseModel):
    """
    Input event data for the detection module. This represents a video that is passed into the detection module.
    """
    model_config = ConfigDict(arbitrary_types_allowed=True)

    video_path: str
    version: str = "0.1.0"


class DetectionOutput(BaseModel):
    """
    Output event data for the detection module. This represents all of the different objects that were detected from the detection module and their corresponding locations in the video.

    Attribute:
    - output_video_path (str): The path to the annotated video that was generated by the detection module.
    - annotated_frames (list[DetectionFrame]): A list of detected frames with their corresponding bounding boxes and labels.
    """
    model_config = ConfigDict(arbitrary_types_allowed=True)

    output_video_path: str
    annotated_frames: list[DetectionFrame]
    version: str = "0.1.0"